// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfLp9eJ-eZU3ZBX9UEE5M-iRcGF34M9-4',
    appId: '1:611234024220:web:36a72a3edb3f69e964c8d9',
    messagingSenderId: '611234024220',
    projectId: 'flutterfire-c2527',
    authDomain: 'flutterfire-c2527.firebaseapp.com',
    databaseURL: 'https://flutterfire-c2527-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfire-c2527.appspot.com',
    measurementId: 'G-8JEJCD41EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYa5_912jKY0Bb7O6BYDHGUmkVCkOAU-E',
    appId: '1:611234024220:android:f6a7e0c09be7c5c564c8d9',
    messagingSenderId: '611234024220',
    projectId: 'flutterfire-c2527',
    databaseURL: 'https://flutterfire-c2527-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfire-c2527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWosdkP46Cu_fC8xXOQ_m_BSD4_pCkWJc',
    appId: '1:611234024220:ios:936839411c7019d264c8d9',
    messagingSenderId: '611234024220',
    projectId: 'flutterfire-c2527',
    databaseURL: 'https://flutterfire-c2527-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfire-c2527.appspot.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWosdkP46Cu_fC8xXOQ_m_BSD4_pCkWJc',
    appId: '1:611234024220:ios:e9c3e962ae5f1ef464c8d9',
    messagingSenderId: '611234024220',
    projectId: 'flutterfire-c2527',
    databaseURL: 'https://flutterfire-c2527-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfire-c2527.appspot.com',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );
}
